# -*- coding: utf-8 -*-
"""
/***************************************************************************
 d4cAPI
                                 A QGIS plugin
 Using d4c api to manipulate ckan data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-09-29
        copyright            : (C) 2023 by MSE @ BPM-conseil
        email                : matthieu.serek@bpm-conseil.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load d4cAPI class from file d4cAPI.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    try:
        import importlib
        importlib.import_module('cryptography')
    except ImportError:
        import subprocess
        subprocess.check_call(['pip', 'install', 'cryptography'])
    from .d4c_api import d4cAPI
    return d4cAPI(iface)
