# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd4c_api_dialog_params.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from qgis.PyQt.QtWidgets import QMessageBox
import os, json

class Ui_Params(object):
    def setupUi(self, Params):
        Params.setObjectName("Params")
        Params.resize(400, 221)
        self.label = QtWidgets.QLabel(Params)
        self.label.setGeometry(QtCore.QRect(20, 40, 261, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Params)
        self.lineEdit.setGeometry(QtCore.QRect(20, 60, 301, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.languageBox = QtWidgets.QComboBox(Params)
        self.languageBox.setGeometry(QtCore.QRect(20, 120, 69, 31))
        self.languageBox.setObjectName("languageBox")
        self.label_2 = QtWidgets.QLabel(Params)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 47, 13))
        self.label_2.setObjectName("label_2")
        self.pushOk = QtWidgets.QPushButton(Params)
        self.pushOk.setGeometry(QtCore.QRect(240, 190, 75, 23))
        self.pushOk.setObjectName("pushOk")
        self.pushCancel = QtWidgets.QPushButton(Params)
        self.pushCancel.setGeometry(QtCore.QRect(320, 190, 75, 23))
        self.pushCancel.setObjectName("pushCancel")
        self.pushBrowse = QtWidgets.QPushButton(Params)
        self.pushBrowse.setGeometry(QtCore.QRect(330, 60, 51, 23))
        self.pushBrowse.setObjectName("pushBrowse")
        

        self.retranslateUi(Params)
        QtCore.QMetaObject.connectSlotsByName(Params)

    def retranslateUi(self, Params):
        _translate = QtCore.QCoreApplication.translate
        Params.setWindowTitle(_translate("Params", "Paramètres"))
        self.label.setText(_translate("Params", "Emplacement de sauvegarde des fichiers : "))
        self.label_2.setText(_translate("Params", "Langue :"))
        self.pushOk.setText(_translate("Params", "Ok"))
        self.pushCancel.setText(_translate("Params", "Annuler"))
        self.pushBrowse.setText(_translate("Params", "..."))

