# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd4c_api_dialog_geoparams.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GeoParams(object):
    def setupUi(self, GeoParams):
        GeoParams.setObjectName("GeoParams")
        GeoParams.resize(331, 232)
        self.lineGeo1 = QtWidgets.QComboBox(GeoParams)
        self.lineGeo1.setGeometry(QtCore.QRect(40, 110, 251, 20))
        self.lineGeo1.setObjectName("lineGeo1")
        self.lineGeo2 = QtWidgets.QComboBox(GeoParams)
        self.lineGeo2.setGeometry(QtCore.QRect(40, 150, 251, 20))
        self.lineGeo2.setObjectName("lineGeo2")
        self.comboColumnType = QtWidgets.QComboBox(GeoParams)
        self.comboColumnType.setGeometry(QtCore.QRect(40, 50, 251, 22))
        self.comboColumnType.setObjectName("comboColumnType")
        self.comboColumnType.addItem("")
        self.comboColumnType.addItem("")
        self.label_column = QtWidgets.QLabel(GeoParams)
        self.label_column.setGeometry(QtCore.QRect(40, 30, 47, 13))
        self.label_column.setObjectName("label_column")
        self.label_lat = QtWidgets.QLabel(GeoParams)
        self.label_lat.setGeometry(QtCore.QRect(40, 93, 191, 16))
        self.label_lat.setObjectName("label_lat")
        self.label_lon = QtWidgets.QLabel(GeoParams)
        self.label_lon.setGeometry(QtCore.QRect(40, 134, 191, 16))
        self.label_lon.setObjectName("label_lon")
        self.pushAddGeoParam = QtWidgets.QPushButton(GeoParams)
        self.pushAddGeoParam.setGeometry(QtCore.QRect(160, 200, 75, 23))
        self.pushAddGeoParam.setObjectName("pushAddGeoParam")
        self.pushCancel = QtWidgets.QPushButton(GeoParams)
        self.pushCancel.setGeometry(QtCore.QRect(240, 200, 75, 23))
        self.pushCancel.setObjectName("pushCancel")
        self.pushDeleteWord = QtWidgets.QPushButton(GeoParams)
        self.pushDeleteWord.setGeometry(QtCore.QRect(10, 200, 101, 23)) 
        self.pushDeleteWord.setObjectName("pushDeleteWord")

        self.retranslateUi(GeoParams)
        QtCore.QMetaObject.connectSlotsByName(GeoParams)

    def retranslateUi(self, GeoParams):
        _translate = QtCore.QCoreApplication.translate
        GeoParams.setWindowTitle(_translate("GeoParams", "Ajouter des colonnes géographiques"))
        self.comboColumnType.setItemText(0, _translate("GeoParams", "Une colonne"))
        self.comboColumnType.setItemText(1, _translate("GeoParams", "Deux colonnes"))
        self.label_column.setText(_translate("GeoParams", "Colonne :"))
        self.label_lat.setText(_translate("GeoParams", "Nom de la colonne :"))
        self.label_lon.setText(_translate("GeoParams", "Libellé longitude :"))
        self.pushAddGeoParam.setText(_translate("GeoParams", "Ajouter"))
        self.pushCancel.setText(_translate("GeoParams", "Fermer"))
        self.pushDeleteWord.setText(_translate("GeoParams", "Supprimer"))
