# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd4c_api_dialog_deletegeoparam.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DeleteGeoParam(object):
    def setupUi(self, DeleteGeoParam):
        DeleteGeoParam.setObjectName("DeleteGeoParam")
        DeleteGeoParam.resize(331, 124)
        self.pushDelete = QtWidgets.QPushButton(DeleteGeoParam)
        self.pushDelete.setGeometry(QtCore.QRect(160, 90, 75, 23))
        self.pushDelete.setObjectName("pushDelete")
        self.pushCancel = QtWidgets.QPushButton(DeleteGeoParam)
        self.pushCancel.setGeometry(QtCore.QRect(240, 90, 75, 23))
        self.pushCancel.setObjectName("pushCancel")
        self.comboBox_wordToDelete = QtWidgets.QComboBox(DeleteGeoParam)
        self.comboBox_wordToDelete.setGeometry(QtCore.QRect(50, 50, 231, 22))
        self.comboBox_wordToDelete.setObjectName("comboBox_wordToDelete")
        self.label = QtWidgets.QLabel(DeleteGeoParam)
        self.label.setGeometry(QtCore.QRect(50, 30, 181, 16))
        self.label.setObjectName("label")

        self.retranslateUi(DeleteGeoParam)
        QtCore.QMetaObject.connectSlotsByName(DeleteGeoParam)

    def retranslateUi(self, DeleteGeoParam):
        _translate = QtCore.QCoreApplication.translate
        DeleteGeoParam.setWindowTitle(_translate("DeleteGeoParam", "Supprimer un élément"))
        self.pushDelete.setText(_translate("DeleteGeoParam", "Supprimer"))
        self.pushCancel.setText(_translate("DeleteGeoParam", "Annuler"))
        self.label.setText(_translate("DeleteGeoParam", "Sélectionner l\'élément à supprimer : "))
