# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd4c_api_dialog_plugininfos.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pluginInfos(object):
    def setupUi(self, pluginInfos):
        pluginInfos.setObjectName("pluginInfos")
        pluginInfos.resize(323, 228)
        self.label_pluginversion = QtWidgets.QLabel(pluginInfos)
        self.label_pluginversion.setGeometry(QtCore.QRect(10, 10, 301, 211))
        self.label_pluginversion.setFrameShape(QtWidgets.QFrame.Box)
        self.label_pluginversion.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_pluginversion.setLineWidth(1)
        self.label_pluginversion.setObjectName("label_pluginversion")

        self.retranslateUi(pluginInfos)
        QtCore.QMetaObject.connectSlotsByName(pluginInfos)

    def retranslateUi(self, pluginInfos):
        _translate = QtCore.QCoreApplication.translate
        pluginInfos.setWindowTitle(_translate("pluginInfos", "Informations du Plugin"))
        self.label_pluginversion.setText(_translate("pluginInfos", "<html><head/><body><p>Détail de l\'extension :</p><p>Cette extension utilise l\'API de Data4Citizen afin de manipuler des Jeux de Données depuis Qgis.</p><p>Auteur : Matthieu Serek @ BPM-conseil<br/><br/>Contact : matthieu.serek@bpm-conseil.com</p><p>Git :<a href=\"https://github.com/Riyolait/d4c-qgis-extension\"> https://github.com/Riyolait/d4c-qgis-extension</a></p><p>BPM-Conseil :<a href=\"http://www.bpm-conseil.com/fr\"> http://www.bpm-conseil.com/fr</p><p>Librairie(s) Python Externe : cryptography</a></p><p>Version : v1.3</p></body></html>"))
